# Generated by Django 3.2.5 on 2022-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bLink', models.CharField(max_length=1000)),
                ('shLink', models.CharField(max_length=20)),
            ],
        ),
    ]
